import type { Clothing, Outfit } from './Wardrobe';

export const CLOTHES: Clothing[] = [
  {
    id: 'dress-white',
    name: 'Белое платье',
    category: 'tops',
    season: 'summer',
    colorScheme: 'light',
    imageUrl: '~/assets/outfit_1.png',
  },
  {
    id: 'scarf-blue',
    name: 'Голубой шарф',
    category: 'accessories',
    season: 'winter',
    colorScheme: 'bright',
    imageUrl: '~/assets/sharf.png',
  },
  {
    id: 'scarf-red',
    name: 'Бордовый шарф',
    category: 'accessories',
    season: 'autumn',
    colorScheme: 'dark',
    imageUrl: '~/assets/sharf.png',
  },
  {
    id: 'boots-black',
    name: 'Чёрные ботинки',
    category: 'shoes',
    season: 'winter',
    colorScheme: 'dark',
    imageUrl: '~/assets/boots.png',
  },
  {
    id: 'shirt-blue',
    name: 'Синяя футболка',
    category: 'tops',
    season: 'summer',
    colorScheme: 'bright',
    imageUrl: '~/assets/outfit 2.png',
  },
  {
    id: 'shirt-yellow',
    name: 'Жёлтая футболка',
    category: 'tops',
    season: 'summer',
    colorScheme: 'bright',
    emoji: '👕',
    fillColor: '#f5e36c',
  },
  {
    id: 'jeans-blue',
    name: 'Синие джинсы',
    category: 'pants',
    season: 'spring',
    colorScheme: 'neutral',
    emoji: '👖',
    fillColor: '#d9dff2',
  },
];

export const STANDARD_CLOTHES: Clothing[] = [
  {
    id: 'standard-shirt-white',
    name: 'Белая футболка',
    category: 'tops',
    season: 'summer',
    colorScheme: 'light',
    emoji: '👕',
    fillColor: '#f3f3f3',
  },
  {
    id: 'standard-pants-white',
    name: 'Белые брюки',
    category: 'pants',
    season: 'summer',
    colorScheme: 'light',
    emoji: '👖',
    fillColor: '#f7f4ef',
  },
  {
    id: 'standard-pants-black',
    name: 'Чёрные брюки',
    category: 'pants',
    season: 'autumn',
    colorScheme: 'dark',
    emoji: '👖',
    fillColor: '#2b2b2b',
  },
  {
    id: 'standard-shirt-folded',
    name: 'Белая рубашка',
    category: 'tops',
    season: 'spring',
    colorScheme: 'light',
    emoji: '👔',
    fillColor: '#eff2f7',
  },
  {
    id: 'standard-shirt-blue',
    name: 'Голубая рубашка',
    category: 'tops',
    season: 'spring',
    colorScheme: 'bright',
    emoji: '👔',
    fillColor: '#d7e7fb',
  },
  {
    id: 'standard-bag',
    name: 'Сумка',
    category: 'accessories',
    season: 'autumn',
    colorScheme: 'dark',
    emoji: '👜',
    fillColor: '#3a3a3a',
  },
];

export const OUTFITS: Outfit[] = [
  {
    id: '1',
    name: 'Белое платье',
    items: ['dress-white', 'boots-black'],
    style: 'evening',
    season: 'winter',
    colorScheme: 'light',
    imageUrl: '~/assets/outfit_1.png',
    views: 124,
  },
  {
    id: '2',
    name: 'Пиджак и юбка',
    items: ['shirt-blue', 'boots-black'],
    style: 'business',
    season: 'autumn',
    colorScheme: 'dark',
    imageUrl: '~/assets/outfit 2.png',
    views: 98,
  },
  {
    id: '3',
    name: 'Лёгкий образ',
    items: ['dress-white', 'scarf-blue'],
    style: 'casual',
    season: 'summer',
    colorScheme: 'light',
    imageUrl: '~/assets/outfit_1.png',
    views: 76,
  },
  {
    id: '4',
    name: 'Городской образ',
    items: ['shirt-blue', 'jeans-blue', 'boots-black'],
    style: 'sport',
    season: 'spring',
    colorScheme: 'neutral',
    imageUrl: '~/assets/outfit 2.png',
    views: 64,
  },
];
