import type { Clothing, Outfit } from './Wardrobe';

export const CLOTHES: Clothing[] = [
  {
    id: 'dress-white',
    name: 'Белая футболка',
    category: 'tops',
    season: 'summer',
    colorScheme: 'light',
    source: 'user',
    imageUrl: '~/assets/baseClothes/white_tshirt.png',
  },
  {
    id: 'scarf-blue',
    name: 'Узорный шарф',
    category: 'accessories',
    season: 'autumn',
    colorScheme: 'bright',
    source: 'user',
    imageUrl: '~/assets/baseClothes/scarf_pattern.png',
  },
  {
    id: 'scarf-red',
    name: 'Красный шарф',
    category: 'accessories',
    season: 'autumn',
    colorScheme: 'dark',
    source: 'user',
    imageUrl: '~/assets/baseClothes/sharf.png',
  },
  {
    id: 'boots-black',
    name: 'Черные ботинки',
    category: 'shoes',
    season: 'winter',
    colorScheme: 'dark',
    source: 'user',
    imageUrl: '~/assets/baseClothes/boots.png',
  },
  {
    id: 'shirt-blue',
    name: 'Темная футболка',
    category: 'tops',
    season: 'summer',
    colorScheme: 'dark',
    source: 'user',
    imageUrl: '~/assets/baseClothes/blue_shirt.png',
  },
  {
    id: 'shirt-yellow',
    name: 'Спортивные перчатки',
    category: 'accessories',
    season: 'winter',
    colorScheme: 'neutral',
    source: 'user',
    imageUrl: '~/assets/baseClothes/gloves.png',
  },
  {
    id: 'jeans-blue',
    name: 'Синие джинсы',
    category: 'pants',
    season: 'autumn',
    colorScheme: 'dark',
    source: 'user',
    imageUrl: '~/assets/baseClothes/pants_blue.png',
  },
];

export const STANDARD_CLOTHES: Clothing[] = [
  {
    id: 'standard-shirt-white',
    name: 'Белая футболка',
    category: 'tops',
    season: 'summer',
    colorScheme: 'light',
    source: 'standard',
    imageUrl: '~/assets/baseClothes/white_tshirt.png',
  },
  {
    id: 'standard-pants-white',
    name: 'Синие джинсы',
    category: 'pants',
    season: 'spring',
    colorScheme: 'dark',
    source: 'standard',
    imageUrl: '~/assets/baseClothes/pants_blue.png',
  },
  {
    id: 'standard-pants-black',
    name: 'Темные брюки',
    category: 'pants',
    season: 'autumn',
    colorScheme: 'dark',
    source: 'standard',
    imageUrl: '~/assets/baseClothes/basic_trousers.png',
  },
  {
    id: 'standard-shirt-folded',
    name: 'Розовая рубашка',
    category: 'tops',
    season: 'spring',
    colorScheme: 'bright',
    source: 'standard',
    imageUrl: '~/assets/baseClothes/dress_shirt.png',
  },
  {
    id: 'standard-shirt-blue',
    name: 'Темная футболка',
    category: 'tops',
    season: 'summer',
    colorScheme: 'dark',
    source: 'standard',
    imageUrl: '~/assets/baseClothes/blue_shirt.png',
  },
  {
    id: 'standard-bag',
    name: 'Белый свитер',
    category: 'tops',
    season: 'winter',
    colorScheme: 'light',
    source: 'standard',
    imageUrl: '~/assets/baseClothes/white_sweater.png',
  },
  {
    id: 'standard-boots-black',
    name: 'Черные ботинки',
    category: 'shoes',
    season: 'winter',
    colorScheme: 'dark',
    source: 'standard',
    imageUrl: '~/assets/baseClothes/boots.png',
  },
  {
    id: 'standard-sneakers-black',
    name: 'Черные кроссовки',
    category: 'shoes',
    season: 'spring',
    colorScheme: 'dark',
    source: 'standard',
    imageUrl: '~/assets/baseClothes/sneakers_black.png',
  },
  {
    id: 'standard-gloves-sport',
    name: 'Спортивные перчатки',
    category: 'accessories',
    season: 'winter',
    colorScheme: 'neutral',
    source: 'standard',
    imageUrl: '~/assets/baseClothes/gloves.png',
  },
  {
    id: 'standard-scarf-pattern',
    name: 'Узорный шарф',
    category: 'accessories',
    season: 'autumn',
    colorScheme: 'bright',
    source: 'standard',
    imageUrl: '~/assets/baseClothes/scarf_pattern.png',
  },
  {
    id: 'standard-scarf-red',
    name: 'Красный шарф',
    category: 'accessories',
    season: 'winter',
    colorScheme: 'dark',
    source: 'standard',
    imageUrl: '~/assets/baseClothes/sharf.png',
  },
];

export const OUTFITS: Outfit[] = [
  {
    id: '1',
    name: 'Городской минимум',
    items: ['standard-shirt-white', 'standard-pants-white', 'standard-boots-black'],
    style: 'casual',
    season: 'spring',
    colorScheme: 'dark',
    imageUrl: '~/assets/baseClothes/white_tshirt.png',
    views: 124,
  },
  {
    id: '2',
    name: 'Прохладная прогулка',
    items: ['standard-bag', 'standard-pants-black', 'standard-scarf-pattern', 'standard-boots-black'],
    style: 'casual',
    season: 'autumn',
    colorScheme: 'neutral',
    imageUrl: '~/assets/baseClothes/white_sweater.png',
    views: 98,
  },
  {
    id: '3',
    name: 'Спортивный день',
    items: ['standard-shirt-blue', 'standard-sneakers-black', 'standard-gloves-sport'],
    style: 'sport',
    season: 'spring',
    colorScheme: 'dark',
    imageUrl: '~/assets/baseClothes/sneakers_black.png',
    views: 76,
  },
  {
    id: '4',
    name: 'Шарф как акцент',
    items: ['standard-shirt-folded', 'standard-pants-white', 'standard-scarf-red', 'standard-boots-black'],
    style: 'business',
    season: 'autumn',
    colorScheme: 'bright',
    imageUrl: '~/assets/baseClothes/dress_shirt.png',
    views: 64,
  },
];
